/**************************************
* THIS FILE IS GENERATED BY TOOL
* DO NOT MODIFY THIS FILE MANUALLY
***************************************/

#ifndef VERSION_H
#define VERSION_H

#define SVN_REV 30764
#define SVN_REV_TIME "2022/11/15 15:55:41"
#define BUILD_TIME "2022/11/15 15:59:53"
#define SVN_URL "https://192.168.1.150:8443/svn/products/vci8_eth/trunk"
#define WORK_AREA_LOCAL_MODIFIED 0
#define WORK_AREA_MOD_IND "REL"



#endif
